import { z } from "zod";

export const AgentRoleSchema = z
  .enum(["orchestrator", "researcher", "builder", "auditor"])
  .describe("The role/type of the agent in the swarm");

export const AgentStatusSchema = z
  .enum(["idle", "thinking", "waiting", "acting", "done", "error", "blocked", "escalated", "rejected"])
  .describe("Current operational status of the agent");

export const AgentSchema = z.object({
  id: z.string().describe("Unique identifier for the agent"),
  name: z.string().describe("Display name of the agent"),
  role: AgentRoleSchema,
  status: AgentStatusSchema,
  parentId: z.string().optional().describe("ID of parent agent if spawned by another"),
});

export const AgentInputSchema = z.object({
  runId: z.string().describe("ID of the current run"),
  task: z.string().describe("Task description for the agent to execute"),
  context: z.record(z.string(), z.unknown()).optional().describe("Additional context data"),
});

export const AgentOutputSchema = z.object({
  status: z
    .enum(["success", "error"])
    .describe("Outcome status of agent execution"),
  result: z.unknown().optional().describe("Result data from execution"),
  artifacts: z
    .array(
      z.object({
        name: z.string().describe("Name of the artifact"),
        content: z.string().describe("Content of the artifact"),
        contentType: z.string().optional().describe("MIME type of the content"),
      })
    )
    .optional()
    .describe("Artifacts generated by the agent"),
  proposals: z
    .array(
      z.object({
        actionId: z.string().describe("Unique ID for this action proposal"),
        kind: z.string().describe("Type of action being proposed"),
        title: z.string().describe("Short title describing the action"),
        rationale: z.string().optional().describe("Why this action is recommended"),
        risk: z.enum(["low", "medium", "high", "critical"]).optional().describe("Risk level"),
      })
    )
    .optional()
    .describe("Action proposals requiring approval"),
});

export type Agent = z.infer<typeof AgentSchema>;
export type AgentRole = z.infer<typeof AgentRoleSchema>;
export type AgentStatusType = z.infer<typeof AgentStatusSchema>;
export type AgentInput = z.infer<typeof AgentInputSchema>;
export type AgentOutput = z.infer<typeof AgentOutputSchema>;
